AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create EC2 instance and Security Group
  In the Exiting VPC
Resources:
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable inbound on tcp port 80
      VpcId: vpc-0e15fa3b1c7fdb852
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: My Security Group
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: "ami-0ca285d4c2cda3300"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: mySecurityGroup
              SubnetId: subnet-001db6d37bcd68875
      UserData:
        Fn::Base64: !Sub |
          #!bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
