AWSTemplateFormatVersion: 2010-09-09
Description: Using Outputs
Resources:
    Outputs: 
        MyVPC3093: 
            Description: A reference to the created VPC
            Value: !Ref MyVPC3093
            Export:
              Name: !Sub ${EnvironmentName}-VPCID

        VPCPublicRouteTable:
            Description: Public Routing
            Value: !Ref PublicRouteTable
            Export:
              Name: !Sub ${EnvironmentName}-PUB-RT

        VPCPrivateRouteTable1:
            Description: Private Routing AZ1
            Value: !Ref PrivateRouteTable1
            Export:
              Name: !Sub ${EnvironmentName}-PRI1-RT

        VPCPrivateRouteTable2:
            Description: Private Routing AZ2
            Value: !Ref PrivateRouteTable2
            Export:
              Name: !Sub ${EnvironmentName}-PRI2-RT

        PublicSubnets:
            Description: A list of the public subnets
            Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
            Export:
              Name: !Sub ${EnvironmentName}-PUB-NETS

        PrivateSubnets:
            Description: A list of the private subnets
            Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
            Export:
              Name: !Sub ${EnvironmentName}-PRIV-NETS

        PublicSubnet1:
            Description: A reference to the public subnet in the 1st Availability Zone
            Value: !Ref PublicSubnet1
            Export:
              Name: !Sub ${EnvironmentName}-PUB1-SN

        PublicSubnet2: 
            Description: A reference to the public subnet in the 2nd Availability Zone
            Value: !Ref PublicSubnet2
            Export:
              Name: !Sub ${EnvironmentName}-PUB2-SN

        PrivateSubnet1:
            Description: A reference to the private subnet in the 1st Availability Zone
            Value: !Ref PrivateSubnet1
            Export:
              Name: !Sub ${EnvironmentName}-PRI1-SN

        PrivateSubnet2: 
            Description: A reference to the private subnet in the 2nd Availability Zone
            Value: !Ref PrivateSubnet2
            Export:
              Name: !Sub ${EnvironmentName}-PRI2-SN
