AWSTemplateFormatVersion: 2010-09-09
Description: >
  Author: Bongani Mokase
  Deploy a VPC on AWS using YAML
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags: 
        - Key: name
          Value: test1VPC
