AWSTemplateFormatVersion: 2010-09-09
Description: Create a launch configuration
Parameters:
Resources:
  WebAppLauchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0ee8244746ec5d6d4
      InstanceType: t3.medium
      SecurityGroups:
        - !Ref WebServerSG
      BlockDeviceMappings:
        - DeviceName: /dev/sdk
          Ebs:
            VolumeSize: 10
      KeyName: MyKeyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install apache2 -y
          sudo systemctl start apache2.service
  